#!/usr/bin/env bash
#
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root (use sudo)" >&2
   exit 1
fi

apt install -y build-essential git gcc g++ wget zip unzip libboost-all-dev

cd ..
git clone https://github.com/Rrominet/py-utils.git
cd ./py-utils 
chmod +x ./install
./install
cd ..

mkdir -p cpp-utils_dependencies
cd cpp-utils_dependencies

dpdir="$(pwd)"

#get all the dependencies here...
wget https://motion-live.com/fxos/dependencies/json.zip
wget https://motion-live.com/fxos/dependencies/eigen.zip
wget https://motion-live.com/fxos/dependencies/sha3.zip
wget https://motion-live.com/fxos/dependencies/fmodstudioapi20000linux.zip
wget https://motion-live.com/fxos/dependencies/FreeImage.zip
wget https://motion-live.com/fxos/dependencies/FreeImagePlus-build.zip

unzip json.zip
unzip eigen.zip
unzip sha3.zip
unzip fmodstudioapi20000linux.zip
echo "Installing fmod lib on the system (/usr/local/lib)..."
cp fmodstudioapi20000linux/api/core/lib/x86_64/* /usr/local/lib/
echo "Fmod lib installed."

unzip FreeImage.zip
unzip FreeImagePlus-build.zip

rm -rf json.zip eigen.zip sha3.zip fmodstudioapi20000linux.zip FreeImage.zip FreeImagePlus-build.zip

cd ../cpp-utils
chmod +x ./make
mkdir -p build
cd build
../make release libs="$dpdir"
chmod 755 ./libmlapi.so

cp ./libmlapi.so /usr/local/lib/libmlapi.so
chmod +x ../add-local-to-linker
../add-local-to-linker

echo "The shared library libmlapi.so (cpp-utils) is installed in /usr/local/lib/libmlapi.so"
